"""
Multi-turn agentic rollout function for TRL's GRPOTrainer.

Plugs into `GRPOTrainer(rollout_func=...)` so that each GRPO sample is a
full agentic episode: the model emits ``<tool_call>...</tool_call>``,
the tool is executed against the live MetroCrowdManager env, the result
is appended back into the running completion as ``<tool_result>...
</tool_result>``, and generation resumes. Loop continues until the model
produces a turn with no tool call (the final answer) or we hit
``max_tool_turns`` / ``max_completion_len``.

Token bookkeeping for GRPO:
  * Tokens generated by the model: env_mask=1, real per-token logprobs.
  * Tokens we inject as tool results: env_mask=0, logprob=0.0.
  * `_generate` in trl/trainer/grpo_trainer.py pops `env_mask` into
    `tool_mask`, which the loss multiplies into the completion mask so
    tool tokens don't get policy-gradient credit.

We also pass per-sample reward, breakdown, turn_history, final_text and
the initial observation through the trainer's `extra_fields` mechanism
so the reward function can be a thin pass-through (no second env replay).
"""

from __future__ import annotations

import json
import time
from typing import Any, Callable, Dict, List, Optional

import torch
import torch.nn.functional as F
from transformers import StoppingCriteria, StoppingCriteriaList

try:
    from MetroCrowdManager.models import SubmitResponseAction
except ImportError:  # pragma: no cover
    from models import SubmitResponseAction

from openenv.core.env_server.mcp_types import CallToolAction

from training.rollout import (
    SYSTEM_PROMPTS,
    _extract_call_result,
    _unwrap,
    parse_tool_calls,
)


# ---------------------------------------------------------------------------
# Stopping criterion: stop generation as soon as we see ``</tool_call>``
# in the newly-generated tail. Without this the model would keep going
# past the closing tag and waste the per-turn token budget on text that
# we'd just discard.
# ---------------------------------------------------------------------------


class StopOnSubstring(StoppingCriteria):
    def __init__(self, substring: str, tokenizer: Any, prompt_len: int, lookback: int = 32):
        super().__init__()
        self.substring = substring
        self.tokenizer = tokenizer
        self.prompt_len = prompt_len
        self.lookback = lookback

    def __call__(self, input_ids: torch.Tensor, scores: torch.Tensor, **_: Any) -> bool:
        # Decoding the entire sequence each step is expensive; only look
        # at the recent tail. ``</tool_call>`` is short so a 32-token
        # lookback is plenty.
        gen = input_ids[0, self.prompt_len:]
        if gen.numel() == 0:
            return False
        tail = gen[-self.lookback:].tolist()
        text = self.tokenizer.decode(tail, skip_special_tokens=False)
        return self.substring in text


# ---------------------------------------------------------------------------
# Per-turn generation
# ---------------------------------------------------------------------------


def _generate_chunk(
    model: Any,
    tokenizer: Any,
    input_ids: torch.Tensor,
    *,
    max_new_tokens: int,
    temperature: float,
    top_p: float,
    eos_token_id: int,
    pad_token_id: int,
    stop_substring: str,
) -> tuple[List[int], List[float], bool]:
    """Generate one chunk; return (new_token_ids, per_token_logprobs, hit_eos)."""
    prompt_len = input_ids.shape[1]
    stopping = StoppingCriteriaList(
        [StopOnSubstring(stop_substring, tokenizer, prompt_len)]
    )
    with torch.no_grad():
        out = model.generate(
            input_ids=input_ids,
            attention_mask=torch.ones_like(input_ids),
            max_new_tokens=max_new_tokens,
            do_sample=temperature > 0,
            temperature=temperature if temperature > 0 else 1.0,
            top_p=top_p,
            pad_token_id=pad_token_id,
            eos_token_id=eos_token_id,
            stopping_criteria=stopping,
            return_dict_in_generate=True,
            output_scores=True,
        )
    seq = out.sequences[0]
    new_ids = seq[prompt_len:].tolist()
    # Strip a trailing EOS so it's not double-counted in env_mask, but
    # remember we hit it so the outer loop knows to treat the chunk as a
    # final answer.
    hit_eos = bool(new_ids) and new_ids[-1] == eos_token_id
    if hit_eos:
        new_ids = new_ids[:-1]

    # Per-token logprobs of the chosen tokens. ``out.scores`` is a tuple
    # of length == #generated tokens (BEFORE EOS strip). Each entry is
    # the post-processed logits over the vocab for the next-token
    # distribution that produced the corresponding sampled token.
    logprobs: List[float] = []
    scores = out.scores or ()
    for step_idx, score in enumerate(scores):
        if step_idx >= len(new_ids):
            break
        log_probs_full = F.log_softmax(score[0].float(), dim=-1)
        chosen = int(new_ids[step_idx])
        logprobs.append(float(log_probs_full[chosen].item()))
    # Pad if for some reason scores are shorter than new_ids (shouldn't
    # happen with the standard generate path, but be defensive).
    while len(logprobs) < len(new_ids):
        logprobs.append(0.0)

    return new_ids, logprobs, hit_eos


# ---------------------------------------------------------------------------
# Per-sample rollout
# ---------------------------------------------------------------------------


def _format_tool_results_block(call_records: List[Dict[str, Any]]) -> str:
    """One ``<tool_result>`` per executed call, joined by newlines.

    Mirrors the format produced by `agentic_episode_async` /
    `agentic_episode_sync` in training/rollout.py so the model sees the
    same protocol it was prompted to expect.
    """
    blocks = []
    for rec in call_records:
        name = rec.get("name") or "unknown"
        data = rec.get("result")
        try:
            payload = json.dumps(data, default=str)[:512]
        except Exception:
            payload = str(data)[:512]
        blocks.append(f'<tool_result name="{name}">{payload}</tool_result>')
    return "\n".join(blocks)


def _per_sample_rollout(
    *,
    prompt_text: str,
    task_name: str,
    env: Any,
    model: Any,
    tokenizer: Any,
    device: torch.device,
    max_tool_turns: int,
    max_completion_len: int,
    max_new_tokens_per_turn: int,
    temperature: float,
    top_p: float,
    seed: Optional[int],
) -> Dict[str, Any]:
    """Run one full agentic episode for a single prompt."""
    eos_token_id = int(tokenizer.eos_token_id)
    pad_token_id = int(tokenizer.pad_token_id or eos_token_id)

    # Reset the env for this episode. Each rollout is independent — we do
    # NOT share env state across samples (they would otherwise see each
    # other's prior tool calls in their reward computation).
    obs = _unwrap(env.reset(task=task_name, seed=seed))
    initial_observation = {
        "prompt_text": getattr(obs, "prompt_text", "") or prompt_text,
        "passenger_message": getattr(obs, "passenger_message", "") or "",
        "scenario_summary": dict(getattr(obs, "scenario_summary", {}) or {}),
        "current_step": getattr(obs, "current_step", 0),
        "max_steps": getattr(obs, "max_steps", 1),
    }

    prompt_ids = tokenizer.encode(prompt_text, add_special_tokens=False)
    prompt_tensor = torch.tensor([prompt_ids], dtype=torch.long, device=device)

    completion_ids: List[int] = []
    completion_logprobs: List[float] = []
    env_mask: List[int] = []
    turn_history: List[Dict[str, Any]] = []
    raw_chunks: List[str] = []

    final_text = ""
    submitted = False
    submit_obs = None

    for turn_idx in range(max_tool_turns):
        remaining = max_completion_len - len(completion_ids)
        if remaining <= 0:
            break
        budget = min(max_new_tokens_per_turn, remaining)
        cur_input = torch.cat(
            [prompt_tensor, torch.tensor([completion_ids], dtype=torch.long, device=device)],
            dim=1,
        )
        new_ids, new_logprobs, hit_eos = _generate_chunk(
            model,
            tokenizer,
            cur_input,
            max_new_tokens=budget,
            temperature=temperature,
            top_p=top_p,
            eos_token_id=eos_token_id,
            pad_token_id=pad_token_id,
            stop_substring="</tool_call>",
        )

        if not new_ids:
            # Nothing generated — we'd loop forever; bail and force-submit.
            break

        completion_ids.extend(new_ids)
        completion_logprobs.extend(new_logprobs)
        env_mask.extend([1] * len(new_ids))

        chunk_text = tokenizer.decode(new_ids, skip_special_tokens=True)
        raw_chunks.append(chunk_text)
        tool_calls = parse_tool_calls(chunk_text)

        if not tool_calls:
            # Final answer turn (or empty turn that hit EOS).
            final_text = chunk_text.strip()
            submit_step = env.step(
                SubmitResponseAction(
                    content=final_text,
                    metadata={"turn_history": turn_history + [{"text": chunk_text, "tool_calls": []}]},
                )
            )
            submit_obs = _unwrap(submit_step)
            turn_history.append({"text": chunk_text, "tool_calls": []})
            submitted = True
            break

        # Execute the tool call(s) declared in this chunk.
        turn_record: Dict[str, Any] = {"text": chunk_text, "tool_calls": []}
        for tc in tool_calls:
            try:
                result_obs = env.step(
                    CallToolAction(tool_name=tc["name"], arguments=tc["arguments"])
                )
                data, error = _extract_call_result(_unwrap(result_obs))
            except Exception as exc:  # pragma: no cover - defensive
                data, error = None, str(exc)
            turn_record["tool_calls"].append(
                {
                    "name": tc["name"],
                    "arguments": tc["arguments"],
                    "result": data,
                    "error": error,
                }
            )
        turn_history.append(turn_record)

        # Inject the tool result block back into the running completion
        # so the next generate() call sees it. Mark every injected token
        # as env_mask=0 / logprob=0 so it's skipped in the policy loss.
        result_text = _format_tool_results_block(turn_record["tool_calls"])
        # Add a leading newline so the result is visibly separated from
        # the just-generated </tool_call> tag.
        injected_text = "\n" + result_text + "\n"
        injected_ids = tokenizer.encode(injected_text, add_special_tokens=False)
        # Truncate if injection would overflow the completion budget.
        room = max_completion_len - len(completion_ids)
        if room <= 0:
            break
        if len(injected_ids) > room:
            injected_ids = injected_ids[:room]
        completion_ids.extend(injected_ids)
        completion_logprobs.extend([0.0] * len(injected_ids))
        env_mask.extend([0] * len(injected_ids))

        # If the model hit EOS together with a tool call (rare but
        # possible), it had no chance to emit a final answer. Don't
        # break — give it one more turn to react to the tool result.

    if not submitted:
        # Either max_tool_turns or completion budget exhausted before
        # the model produced a tool-free turn. Force a submit so the env
        # still scores us (likely poorly, which is the correct signal).
        forced_text = ""
        # Use the last raw chunk as the "final" text if it had no tool
        # calls, otherwise empty.
        if raw_chunks and not parse_tool_calls(raw_chunks[-1]):
            forced_text = raw_chunks[-1].strip()
        submit_step = env.step(
            SubmitResponseAction(
                content=forced_text,
                metadata={"turn_history": turn_history},
            )
        )
        submit_obs = _unwrap(submit_step)
        final_text = forced_text

    # Truncate to the completion budget (defensive — we should already
    # be under it, but the trainer asserts this).
    if len(completion_ids) > max_completion_len:
        completion_ids = completion_ids[:max_completion_len]
        completion_logprobs = completion_logprobs[:max_completion_len]
        env_mask = env_mask[:max_completion_len]

    reward = float(getattr(submit_obs, "reward", 0.0) or 0.0) if submit_obs is not None else 0.0
    breakdown = dict(getattr(submit_obs, "reward_breakdown", {}) or {}) if submit_obs is not None else {}

    raw_completion = "".join(raw_chunks)

    return {
        "prompt_ids": prompt_ids,
        "completion_ids": completion_ids,
        "logprobs": completion_logprobs,
        "env_mask": env_mask,
        "reward": reward,
        "breakdown": breakdown,
        "turn_history": turn_history,
        "final_text": final_text,
        "raw_completion": raw_completion,
        "initial_observation": initial_observation,
        "system_prompt": SYSTEM_PROMPTS.get(task_name, ""),
    }


# ---------------------------------------------------------------------------
# Public factory
# ---------------------------------------------------------------------------


def make_agentic_rollout_func(
    env: Any,
    *,
    task_resolver: Callable[[int, str], str],
    seed_resolver: Optional[Callable[[int, str], Optional[int]]] = None,
    max_tool_turns: int = 6,
    max_completion_len: int = 1024,
    max_new_tokens_per_turn: int = 192,
    temperature: float = 0.7,
    top_p: float = 0.95,
    log_first_sample_timing: bool = True,
    log_every_sample: bool = True,
) -> Callable[[List[str], Any], Dict[str, Any]]:
    """Build a TRL-compatible `rollout_func`.

    Args:
        env: Live MetroCrowdManager env client (sync). Reused across all
            samples; each sample calls `env.reset(...)` first so episodes
            are isolated.
        task_resolver: Maps (sample_index_within_batch, prompt_text) -> task_name.
            We need this because `rollout_func` only receives the chat-templated
            prompt strings — the trainer doesn't pass the dataset's `task`
            column through. The caller is expected to track the order.
        seed_resolver: Optional. Same idea for per-sample seeds.
        max_tool_turns: Max number of generate->tool->generate cycles.
        max_completion_len: Hard cap on completion token count.
        max_new_tokens_per_turn: Per-turn generation budget.
        temperature, top_p: Sampling.
        log_first_sample_timing: Print per-turn timing for sample 0 of
            each batch so it's easy to spot a runaway turn.
        log_every_sample: When True, print a one-liner for every rollout
            (e.g. ``sample 3/8 task=ticket_booking elapsed=51.4s``) so HF
            Jobs logs visibly tick once per rollout instead of going dark
            for the full ``batch_size * grad_accum`` rollouts between
            optimizer steps.
    """

    def rollout_func(prompts: List[str], trainer: Any) -> Dict[str, Any]:
        model = trainer.model
        tokenizer = trainer.processing_class
        device = trainer.accelerator.device

        prompt_ids_batch: List[List[int]] = []
        completion_ids_batch: List[List[int]] = []
        logprobs_batch: List[List[float]] = []
        env_mask_batch: List[List[int]] = []
        rollout_reward: List[float] = []
        rollout_breakdown: List[Dict[str, float]] = []
        rollout_turn_history: List[List[dict]] = []
        rollout_final_text: List[str] = []
        rollout_raw_completion: List[str] = []
        rollout_initial_obs: List[Dict[str, Any]] = []
        rollout_system_prompt: List[str] = []
        rollout_task_name: List[str] = []

        was_training = model.training
        model.eval()
        try:
            for i, prompt_text in enumerate(prompts):
                task_name = task_resolver(i, prompt_text)
                seed = seed_resolver(i, prompt_text) if seed_resolver else None

                t0 = time.time()
                result = _per_sample_rollout(
                    prompt_text=prompt_text,
                    task_name=task_name,
                    env=env,
                    model=model,
                    tokenizer=tokenizer,
                    device=device,
                    max_tool_turns=max_tool_turns,
                    max_completion_len=max_completion_len,
                    max_new_tokens_per_turn=max_new_tokens_per_turn,
                    temperature=temperature,
                    top_p=top_p,
                    seed=seed,
                )
                elapsed = time.time() - t0
                if log_every_sample:
                    print(
                        f"[rollout] sample {i + 1}/{len(prompts)} task={task_name} "
                        f"comp_len={len(result['completion_ids'])} "
                        f"turns={len(result['turn_history'])} "
                        f"reward={result['reward']:.3f} "
                        f"elapsed={elapsed:.1f}s",
                        flush=True,
                    )
                elif log_first_sample_timing and i == 0:
                    print(
                        f"[rollout] sample0 task={task_name} "
                        f"comp_len={len(result['completion_ids'])} "
                        f"turns={len(result['turn_history'])} "
                        f"elapsed={elapsed:.1f}s",
                        flush=True,
                    )

                prompt_ids_batch.append(result["prompt_ids"])
                completion_ids_batch.append(result["completion_ids"])
                logprobs_batch.append(result["logprobs"])
                env_mask_batch.append(result["env_mask"])
                rollout_reward.append(result["reward"])
                rollout_breakdown.append(result["breakdown"])
                rollout_turn_history.append(result["turn_history"])
                rollout_final_text.append(result["final_text"])
                rollout_raw_completion.append(result["raw_completion"])
                rollout_initial_obs.append(result["initial_observation"])
                rollout_system_prompt.append(result["system_prompt"])
                rollout_task_name.append(task_name)
        finally:
            if was_training:
                model.train()

        return {
            "prompt_ids": prompt_ids_batch,
            "completion_ids": completion_ids_batch,
            "logprobs": logprobs_batch,
            "env_mask": env_mask_batch,
            # Extra fields below are merged into reward_fn kwargs by
            # _generate_and_score_completions (line 2115 of grpo_trainer.py).
            "rollout_reward": rollout_reward,
            "rollout_breakdown": rollout_breakdown,
            "rollout_turn_history": rollout_turn_history,
            "rollout_final_text": rollout_final_text,
            "rollout_raw_completion": rollout_raw_completion,
            "rollout_initial_obs": rollout_initial_obs,
            "rollout_system_prompt": rollout_system_prompt,
            "rollout_task_name": rollout_task_name,
        }

    return rollout_func
